In [1]:
import pandas as pd

In [21]:
lei_df = pd.read_csv("../output/fuzzy_first_run.txt", dtype="object", sep="|")
len(lei_df)

35

In [22]:
lei_df.columns

Index(['city_score', 'gleif_city', 'gleif_lei', 'gleif_name', 'gleif_street',
       'inst_id', 'name_score', 'nic_lei', 'nic_name', 'panel_city',
       'panel_street', 'street_score'],
      dtype='object')

In [23]:
lei_df = lei_df[['inst_id',
                'nic_name',
                'panel_city',
                'panel_street',
                'nic_lei',
                'gleif_lei',
                'gleif_name',
                'gleif_city',
                'gleif_street',
                'city_score',
                'name_score',
                'street_score']].copy()

In [24]:
lei_df["total_score"] = lei_df.apply(lambda x: int(x.city_score) + int(x.name_score) + int(x.street_score), axis=1)
lei_df.sort_values(by="total_score", ascending=False, inplace=True)
lei_df

,inst_id,nic_name,panel_city,panel_street,nic_lei,gleif_lei,gleif_name,gleif_city,gleif_street,city_score,name_score,street_score,total_score
34,176642,LNB COMMUNITY BANK,LYNNVILLE,215 MAIN STREET,213800XA5M2HOWATHG59,213800XA5M2HOWATHG59,LNB COMMUNITY BANK,LYNNVILLE,215 MAIN STREET,100,100,100,300
33,924405,DIME COMMUNITY BANK,BROOKLYN,209 HAVEMEYER STREET,549300RWP6SKF6EZZP82,213800XA5M2HOWATHG59,LNB COMMUNITY BANK,LYNNVILLE,215 MAIN STREET,81,81,57,219
32,3938186,"BANKUNITED, NATIONAL ASSOCIATION",MIAMI LAKES,14817 OAK LANE,BFLFJ4PXRGDML87ZYT33,1IE8VN30JCEQV1H4R804,"HSBC BANK USA, NATIONAL ASSOCIATION",MCLEAN,1800 TYSONS BOULEVARD,81,81,40,202
31,3938186,"BANKUNITED, NATIONAL ASSOCIATION",MIAMI LAKES,14817 OAK LANE,BFLFJ4PXRGDML87ZYT33,549300APS6VPRJNHGH77,INTERNATIONAL BAR ASSOCIATION,ALBANY,1218 CENTRAL AVENUE,75,75,48,198
30,428547,ST. CHARLES BANK & TRUST COMPANY,SAINT CHARLES,411 WEST MAIN STREET,549300UDBUNBNEKR8J69,213800GF3VF8WSF5Q651,FOREST PARK NATIONAL BANK AND TRUST COMPANY,FOREST PARK,7348 W MADISON ST,69,69,59,197
29,474919,"FULTON BANK, NATIONAL ASSOCIATION",LANCASTER,ONE PENN SQUARE,DZC62HF6UIZYJ08V1J90,1IE8VN30JCEQV1H4R804,"HSBC BANK USA, NATIONAL ASSOCIATION",MCLEAN,1800 TYSONS BOULEVARD,79,79,33,191
28,2871099,TRISTAR BANK,DICKSON,719 EAST COLLEGE STREET,549300LTKCJV903ZQR25,254900MDBTY5G03LIX66,INTERCONTINENTAL BANK,MIAMI,5722 SW 8TH STREET,61,61,54,176
27,2871099,TRISTAR BANK,DICKSON,719 EAST COLLEGE STREET,549300LTKCJV903ZQR25,254900KN1X8B3CQDSO97,SUNSTATE BANK,MIAMI,14095 S DIXIE HWY,64,64,35,163
26,2871099,TRISTAR BANK,DICKSON,719 EAST COLLEGE STREET,549300LTKCJV903ZQR25,254900ARLAZ571P0Z136,INDUSTRY STATE BANK,INDUSTRY,16886 FORDTRAN BLVD,65,65,24,154
25,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,254900UKANDAKWQ7CR03,NORTHEAST SECURITY BANK,SUMNER,108 NORTH CARPETNER,51,51,51,153
24,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,254900NLUIQMYI2MW872,GRANDSOUTH BANK,GREENVILLE,381 HALTON ROAD,52,52,47,151
23,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,25490052T4M68YYACN14,QUANTUM NATIONAL BANK,SUWANEE,505 PEACHTREE INDUSTRIAL BLVD,54,54,39,147
22,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,529900O8P8I2P84ZTJ92,DSV AIR & SEA INC.,DOVER,"c/o NATIONAL REGISTERED AGENTS, INC. 160 GREEN...",53,53,36,142
21,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,21380055IMHX3N5UL146,VALLEY STATE BANK,BELLE PLAINE,502 NORTH MERCHANT,48,48,43,139
20,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,213800MWCCDADP38AW10,"MCS DIRECT, INC.",W. BRIDGEWATER,321 MANLEY STREET,50,50,36,136
19,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,2138003T2AVNIFKAIA36,RBS FOUNDATION INC.,NEW CASTLE COUNTY,2711 CENTERVILLE ROAD SUITE 400,40,40,44,124
18,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,213800QC7QOOVXBCE436,DENARIUS FUNDING LLC,WILMINGTON,2711 CENTERVILLE ROAD SUITE 400,39,39,44,122
17,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,213800KOH9RK6QT97D37,DENARIUS FUNDING II LLC,WILMINGTON,2711 CENTERVILLE ROAD SUITE 400,36,36,44,116
16,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,213800P7IFUPXLSI3O07,DR PANAMINT LLC,WILMINGTON,"901 NORTH MARKET STREET, SUITE 705",32,32,45,109
15,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,213800IMDG729RLSUM04,"PALATINE HILLS LEASING, INC.",WILMINGTON,CORPORATION TRUST CENTER,36,36,35,107
14,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,2138002Z7YAJAKZFUK85,HSBC RETAIL CREDIT (USA) INC.,BUFFALO,OFFICE OF GENERAL COUNSEL,36,36,34,106
13,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,213800HKAADHE5IWM916,HFC LEASING INC.,WILMINGTON,C/O THE CORPORATION TRUST COMPANY,31,31,43,105
12,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,213800NAN42LNYBD1Z52,BENEFICIAL CREDIT SERVICES INC.,WILMINGTON,C/O THE CORPORATION TRUST COMPANY,30,30,43,103
11,3603765,ADAMS DAIRY BANK,BLUE SPRINGS,651 NORTHEAST CORONADO DRIVE,549300XVXVMZ9CDXV530,2138008LTICA91ZQKQ29,GROSVENOR BROKERS (AMERICA) LLC,NEW JERSEY,5 NORTHOVER PLACE,21,21,49,91
10,546991,-1,LEAVENWORTH,-1,-1,549300GYWE9LWAHBN706,LABC-17,Lansdale,"C/O Hamburg, Rubin, Mullin & Maxwell Corporati...",44,44,0,88
9,546991,-1,LEAVENWORTH,-1,-1,254900RC7KXX8I79YV78,"RBP-1, LLC",Wareham,c/o ADM Management Corporation,33,33,0,66
8,546991,-1,LEAVENWORTH,-1,-1,254900N96TMY2BDW4S57,"LSC-DD MC1, DST",Wilmington,The Corporation Trust Company,24,24,0,48
7,546991,-1,LEAVENWORTH,-1,-1,2549003OZMJYWXFF9S60,GMS-VANSCO,Petaluma,1310 Redwood Way,17,17,11,45
6,546991,-1,LEAVENWORTH,-1,-1,529900WFHX6GRPXLBU31,T-4 LLC,New york,430 East 56th Street,22,22,0,44
5,546991,-1,LEAVENWORTH,-1,-1,213800OG4MHQSSFI8Y75,"CARD-FLO #1, INC.",WILMINGTON,C/O THE CORPORATION TRUST COMPANY,21,21,0,42
4,546991,-1,LEAVENWORTH,-1,-1,213800S66WA6ACL6L143,"180LA, LLC",SANTA MONICA,"1733 OCEAN AVENUE, 4TH FLOOR",17,17,7,41
3,546991,-1,LEAVENWORTH,-1,-1,213800YAB57IJOMFLZ57,"SLRB-I, LLC",WILMINGTON,CORPORATION SERVICE COMPANY,15,15,0,30
2,546991,-1,LEAVENWORTH,-1,-1,21380048FCCD1JYL8J91,SFR 2010-3 ACQUISITION LLC,WILMINGTON,2711 CENTREVILLE ROAD,7,7,9,23
1,546991,-1,LEAVENWORTH,-1,-1,213800XHK9QDTG1R6S96,"WISSAHICKON REAL ESTATE ALLIANCE, LLC",PHILADELPHIA,1500 WALNUT STREET,0,0,10,10
0,546991,-1,LEAVENWORTH,-1,-1,21380087BAB79DFYRR32,LION COMMERCIAL LLC,WILMINGTON,"108, WEST 13TH STREET",0,0,9,9

In [25]:
len(lei_df)

35

In [26]:
lei_df.tail()

,inst_id,nic_name,panel_city,panel_street,nic_lei,gleif_lei,gleif_name,gleif_city,gleif_street,city_score,name_score,street_score,total_score
4,546991,-1,LEAVENWORTH,-1,-1,213800S66WA6ACL6L143,"180LA, LLC",SANTA MONICA,"1733 OCEAN AVENUE, 4TH FLOOR",17,17,7,41
3,546991,-1,LEAVENWORTH,-1,-1,213800YAB57IJOMFLZ57,"SLRB-I, LLC",WILMINGTON,CORPORATION SERVICE COMPANY,15,15,0,30
2,546991,-1,LEAVENWORTH,-1,-1,21380048FCCD1JYL8J91,SFR 2010-3 ACQUISITION LLC,WILMINGTON,2711 CENTREVILLE ROAD,7,7,9,23
1,546991,-1,LEAVENWORTH,-1,-1,213800XHK9QDTG1R6S96,"WISSAHICKON REAL ESTATE ALLIANCE, LLC",PHILADELPHIA,1500 WALNUT STREET,0,0,10,10
0,546991,-1,LEAVENWORTH,-1,-1,21380087BAB79DFYRR32,LION COMMERCIAL LLC,WILMINGTON,"108, WEST 13TH STREET",0,0,9,9